# traefik — reverse proxy as an isolated Docker Compose stack
#
# Runs Traefik in Docker so it is fully decoupled from the NixOS rebuild
# cycle. A failed rebuild (e.g. a broken crane-services build) will not
# prevent Traefik config changes from taking effect on the next manual
# `docker-compose up -d`.
#
# The static config is generated by Nix and mounted read-only from the
# Nix store. Dynamic config fragments are read from /etc/traefik/conf.d/
# (still written by other NixOS modules via environment.etc) and watched
# for hot-reload — no container restart needed when routes change.
#
# ACME state (/var/lib/traefik/acme.json) is persisted on the host so
# certificates survive container restarts and image upgrades.
{ config, lib, pkgs, ... }:

let
  cfg = config.services.traefik-compose;

  staticConfig = (pkgs.formats.toml { }).generate "traefik-static.toml" {
    entryPoints = {
      web = {
        address = ":80";
        http.redirections.entryPoint = {
          to = "websecure";
          scheme = "https";
          permanent = true;
        };
      };
      websecure.address = ":443";
    };
    certificatesResolvers.cloudflare.acme = {
      email = cfg.acmeEmail;
      storage = "/var/lib/traefik/acme.json";
      dnsChallenge = {
        provider = "cloudflare";
        resolvers = [ "1.1.1.1:53" "1.0.0.1:53" ];
      };
    };
    providers.file = {
      directory = "/etc/traefik/conf.d";
      watch = true;
    };
    log.level = cfg.logLevel;
  };

  # Compose file is generated into the Nix store; the service references it
  # by store path so systemd's restartTriggers picks up config changes.
  composeFile = pkgs.writeText "traefik-compose.yml" ''
    services:
      traefik:
        image: "${cfg.image}"
        network_mode: host
        restart: unless-stopped
        volumes:
          - "${staticConfig}:/etc/traefik/traefik.toml:ro"
          - "/etc/traefik/conf.d:/etc/traefik/conf.d:ro"
          - "/etc/static/traefik:/etc/static/traefik:ro"
          - "/nix/store:/nix/store:ro"
          - "/var/lib/traefik:/var/lib/traefik"
        env_file:
          - "${cfg.cloudflareCredentialsFile}"
  '';

in {
  options.services.traefik-compose = {
    enable = lib.mkEnableOption "Traefik reverse proxy (Docker Compose stack)";

    image = lib.mkOption {
      type = lib.types.str;
      default = "traefik:v3";
      description = "Traefik Docker image and tag to use.";
    };

    acmeEmail = lib.mkOption {
      type = lib.types.str;
      description = "Email address for ACME certificate registration.";
    };

    logLevel = lib.mkOption {
      type = lib.types.str;
      default = "INFO";
      description = "Traefik log level (DEBUG, INFO, WARN, ERROR).";
    };

    cloudflareCredentialsFile = lib.mkOption {
      type = lib.types.path;
      description = ''
        Path to a KEY=VALUE env file containing Cloudflare credentials for
        the ACME DNS challenge (CF_DNS_API_TOKEN, or CF_API_EMAIL +
        CF_API_KEY). Use an agenix secret:
          config.age.secrets.cloudflare-credentials.path
      '';
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Open ports 80 and 443 (TCP + UDP) in the firewall.";
    };
  };

  config = lib.mkIf cfg.enable {
    virtualisation.docker.enable = lib.mkDefault true;

    environment.systemPackages = [ pkgs.docker-compose ];

    # Ensure ACME state directory exists before the container starts.
    systemd.tmpfiles.rules = [
      "d /var/lib/traefik 0700 root root -"
    ];

    systemd.services.traefik-compose = {
      description = "Traefik reverse proxy (Docker Compose)";
      after    = [ "docker.service" "network-online.target" ];
      wants    = [ "network-online.target" ];
      requires = [ "docker.service" ];
      wantedBy = [ "multi-user.target" ];

      # Restart when the generated compose file (and therefore the static
      # config it embeds) changes after a NixOS switch.
      restartTriggers = [ composeFile ];

      serviceConfig = {
        Type            = "oneshot";
        RemainAfterExit = true;
        ExecStart       = "${pkgs.docker-compose}/bin/docker-compose -f ${composeFile} up -d";
        ExecStop        = "${pkgs.docker-compose}/bin/docker-compose -f ${composeFile} down";
        TimeoutStartSec = "5min";
      };
    };

    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedTCPPorts = [ 80 443 ];
      allowedUDPPorts = [ 443 ];
    };
  };
}
