# Hardware configuration for alastor VPS
# Generated by nix-infect on OCI ARM
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # GRUB boot (set up by nix-infect)
  boot.loader.grub = {
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
  };

  # Filesystems
  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3807-C85F";
    fsType = "vfat";
  };

  # OCI/Xen kernel modules
  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "xen_blkfront"
  ];
  boot.initrd.kernelModules = [ "nvme" ];

  # Enable QEMU guest agent for better VM integration
  services.qemuGuest.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
